Update example04

diff --git a/KCW/examples/example04/run_example b/KCW/examples/example04/run_example
--- a/KCW/examples/example04/run_example
+++ b/KCW/examples/example04/run_example
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+nk=3
+
 # run from directory where this script is
 cd `dirname $0`
 EXAMPLE_DIR=`pwd`
@@ -17,7 +19,7 @@ $ECHO "to merge separate wannierizations "
 . ../../../environment_variables
 
 # required executables and pseudopotentials
-BIN_LIST="pw.x kcw.x"
+BIN_LIST="pw.x kcw.x wannier90.x pw2wannier90.x merge_wann.x"
 PSEUDO_LIST="Ga.upf As.upf"
 
 #Overwrite PSEUDO_DIR
@@ -57,6 +59,13 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
+FILE="$BIN_DIR/../external/wannier90/utility/kmesh.pl"
+if test ! -x $FILE ; then
+        $ECHO
+        $ECHO "ERROR: $FILE not existent or not executable"
+        $ECHO "Aborting"
+        exit 1
+    fi
 $ECHO " done"
 
 ##Overwrite NETWORK_PSEUDO
@@ -81,13 +90,17 @@ $ECHO " done"
 
 # how to run executables
 PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
-W90_COMMAND="$BIN_DIR/wannier90.x"
+W90_COMMAND="$PARA_PREFIX $BIN_DIR/wannier90.x"
 PW2W90_COMMAND="$PARA_PREFIX $BIN_DIR/pw2wannier90.x"
 KCW_COMMAND_noPOSTFIX="$PARA_PREFIX $BIN_DIR/kcw.x"
 KCW_COMMAND="$PARA_PREFIX $BIN_DIR/kcw.x $PARA_POSTFIX"
+MERGE_WANN_COMMAND="$BIN_DIR/merge_wann.x"
+KMESH_COMMAND="$BIN_DIR/../external/wannier90/utility/kmesh.pl"
 $ECHO
-$ECHO "  running pw.x as:   $PW_COMMAND"
-$ECHO "  running kcw.x as:   $KCW_COMMAND"
+$ECHO "  running pw.x as:            $PW_COMMAND"
+$ECHO "  running kcw.x as:           $KCW_COMMAND"
+$ECHO "  running wannier90.x as:     $W90_COMMAND"
+$ECHO "  running pw2wannier90.x as:  $PW2W90_COMMAND"
 $ECHO
 
 # clean TMP_DIR
@@ -143,6 +156,8 @@ $ECHO "  Running the SCF calculation for $PREFIX...\c"
 $PW_COMMAND < $PREFIX.scf.in > $PREFIX.scf.out
 $ECHO " done"
 
+$KMESH_COMMAND $nk $nk $nk  > k_points.txt
+
 cat > $PREFIX.nscf.in << EOF
 &CONTROL
   calculation = 'nscf'
@@ -182,79 +197,18 @@ CELL_PARAMETERS angstrom
     2.8260000000     0.0000000000     2.8260000000
     2.8260000000     2.8260000000     0.0000000000
 
-K_POINTS crystal
-64
-  0.00000000  0.00000000  0.00000000  1.562500e-02
-  0.00000000  0.00000000  0.25000000  1.562500e-02
-  0.00000000  0.00000000  0.50000000  1.562500e-02
-  0.00000000  0.00000000  0.75000000  1.562500e-02
-  0.00000000  0.25000000  0.00000000  1.562500e-02
-  0.00000000  0.25000000  0.25000000  1.562500e-02
-  0.00000000  0.25000000  0.50000000  1.562500e-02
-  0.00000000  0.25000000  0.75000000  1.562500e-02
-  0.00000000  0.50000000  0.00000000  1.562500e-02
-  0.00000000  0.50000000  0.25000000  1.562500e-02
-  0.00000000  0.50000000  0.50000000  1.562500e-02
-  0.00000000  0.50000000  0.75000000  1.562500e-02
-  0.00000000  0.75000000  0.00000000  1.562500e-02
-  0.00000000  0.75000000  0.25000000  1.562500e-02
-  0.00000000  0.75000000  0.50000000  1.562500e-02
-  0.00000000  0.75000000  0.75000000  1.562500e-02
-  0.25000000  0.00000000  0.00000000  1.562500e-02
-  0.25000000  0.00000000  0.25000000  1.562500e-02
-  0.25000000  0.00000000  0.50000000  1.562500e-02
-  0.25000000  0.00000000  0.75000000  1.562500e-02
-  0.25000000  0.25000000  0.00000000  1.562500e-02
-  0.25000000  0.25000000  0.25000000  1.562500e-02
-  0.25000000  0.25000000  0.50000000  1.562500e-02
-  0.25000000  0.25000000  0.75000000  1.562500e-02
-  0.25000000  0.50000000  0.00000000  1.562500e-02
-  0.25000000  0.50000000  0.25000000  1.562500e-02
-  0.25000000  0.50000000  0.50000000  1.562500e-02
-  0.25000000  0.50000000  0.75000000  1.562500e-02
-  0.25000000  0.75000000  0.00000000  1.562500e-02
-  0.25000000  0.75000000  0.25000000  1.562500e-02
-  0.25000000  0.75000000  0.50000000  1.562500e-02
-  0.25000000  0.75000000  0.75000000  1.562500e-02
-  0.50000000  0.00000000  0.00000000  1.562500e-02
-  0.50000000  0.00000000  0.25000000  1.562500e-02
-  0.50000000  0.00000000  0.50000000  1.562500e-02
-  0.50000000  0.00000000  0.75000000  1.562500e-02
-  0.50000000  0.25000000  0.00000000  1.562500e-02
-  0.50000000  0.25000000  0.25000000  1.562500e-02
-  0.50000000  0.25000000  0.50000000  1.562500e-02
-  0.50000000  0.25000000  0.75000000  1.562500e-02
-  0.50000000  0.50000000  0.00000000  1.562500e-02
-  0.50000000  0.50000000  0.25000000  1.562500e-02
-  0.50000000  0.50000000  0.50000000  1.562500e-02
-  0.50000000  0.50000000  0.75000000  1.562500e-02
-  0.50000000  0.75000000  0.00000000  1.562500e-02
-  0.50000000  0.75000000  0.25000000  1.562500e-02
-  0.50000000  0.75000000  0.50000000  1.562500e-02
-  0.50000000  0.75000000  0.75000000  1.562500e-02
-  0.75000000  0.00000000  0.00000000  1.562500e-02
-  0.75000000  0.00000000  0.25000000  1.562500e-02
-  0.75000000  0.00000000  0.50000000  1.562500e-02
-  0.75000000  0.00000000  0.75000000  1.562500e-02
-  0.75000000  0.25000000  0.00000000  1.562500e-02
-  0.75000000  0.25000000  0.25000000  1.562500e-02
-  0.75000000  0.25000000  0.50000000  1.562500e-02
-  0.75000000  0.25000000  0.75000000  1.562500e-02
-  0.75000000  0.50000000  0.00000000  1.562500e-02
-  0.75000000  0.50000000  0.25000000  1.562500e-02
-  0.75000000  0.50000000  0.50000000  1.562500e-02
-  0.75000000  0.50000000  0.75000000  1.562500e-02
-  0.75000000  0.75000000  0.00000000  1.562500e-02
-  0.75000000  0.75000000  0.25000000  1.562500e-02
-  0.75000000  0.75000000  0.50000000  1.562500e-02
-  0.75000000  0.75000000  0.75000000  1.562500e-02
+$(cat k_points.txt)
 EOF
 $ECHO "  Running the NSCF calculation for $PREFIX...\c"
 $PW_COMMAND < $PREFIX.nscf.in > $PREFIX.nscf.out
+rm k_points.txt 
 $ECHO " done"
 
 if [ ! -d wann_block1 ]; then  mkdir wann_block1 ; fi
 cd wann_block1
+
+$KMESH_COMMAND $nk $nk $nk  wann > k_points.txt
+
 cat > $SEEDNAME.win << EOF
 num_bands         =   5
 num_wann          =   5
@@ -300,73 +254,10 @@ end kpoint_path
 
 
 
-mp_grid      = 4 4 4
+mp_grid      = $nk $nk $nk
 
 begin kpoints
-  0.00000000  0.00000000  0.00000000
-  0.00000000  0.00000000  0.25000000
-  0.00000000  0.00000000  0.50000000
-  0.00000000  0.00000000  0.75000000
-  0.00000000  0.25000000  0.00000000
-  0.00000000  0.25000000  0.25000000
-  0.00000000  0.25000000  0.50000000
-  0.00000000  0.25000000  0.75000000
-  0.00000000  0.50000000  0.00000000
-  0.00000000  0.50000000  0.25000000
-  0.00000000  0.50000000  0.50000000
-  0.00000000  0.50000000  0.75000000
-  0.00000000  0.75000000  0.00000000
-  0.00000000  0.75000000  0.25000000
-  0.00000000  0.75000000  0.50000000
-  0.00000000  0.75000000  0.75000000
-  0.25000000  0.00000000  0.00000000
-  0.25000000  0.00000000  0.25000000
-  0.25000000  0.00000000  0.50000000
-  0.25000000  0.00000000  0.75000000
-  0.25000000  0.25000000  0.00000000
-  0.25000000  0.25000000  0.25000000
-  0.25000000  0.25000000  0.50000000
-  0.25000000  0.25000000  0.75000000
-  0.25000000  0.50000000  0.00000000
-  0.25000000  0.50000000  0.25000000
-  0.25000000  0.50000000  0.50000000
-  0.25000000  0.50000000  0.75000000
-  0.25000000  0.75000000  0.00000000
-  0.25000000  0.75000000  0.25000000
-  0.25000000  0.75000000  0.50000000
-  0.25000000  0.75000000  0.75000000
-  0.50000000  0.00000000  0.00000000
-  0.50000000  0.00000000  0.25000000
-  0.50000000  0.00000000  0.50000000
-  0.50000000  0.00000000  0.75000000
-  0.50000000  0.25000000  0.00000000
-  0.50000000  0.25000000  0.25000000
-  0.50000000  0.25000000  0.50000000
-  0.50000000  0.25000000  0.75000000
-  0.50000000  0.50000000  0.00000000
-  0.50000000  0.50000000  0.25000000
-  0.50000000  0.50000000  0.50000000
-  0.50000000  0.50000000  0.75000000
-  0.50000000  0.75000000  0.00000000
-  0.50000000  0.75000000  0.25000000
-  0.50000000  0.75000000  0.50000000
-  0.50000000  0.75000000  0.75000000
-  0.75000000  0.00000000  0.00000000
-  0.75000000  0.00000000  0.25000000
-  0.75000000  0.00000000  0.50000000
-  0.75000000  0.00000000  0.75000000
-  0.75000000  0.25000000  0.00000000
-  0.75000000  0.25000000  0.25000000
-  0.75000000  0.25000000  0.50000000
-  0.75000000  0.25000000  0.75000000
-  0.75000000  0.50000000  0.00000000
-  0.75000000  0.50000000  0.25000000
-  0.75000000  0.50000000  0.50000000
-  0.75000000  0.50000000  0.75000000
-  0.75000000  0.75000000  0.00000000
-  0.75000000  0.75000000  0.25000000
-  0.75000000  0.75000000  0.50000000
-  0.75000000  0.75000000  0.75000000
+$(cat k_points.txt)
 end kpoints
 EOF
 
@@ -380,13 +271,19 @@ cat > pw2wann.in <<EOF
 /
 EOF
 
-/home/nicola/CODES/q-e-kcw/bin/wannier90.x -pp $SEEDNAME.win
-/home/nicola/CODES/q-e-kcw/bin/pw2wannier90.x -in pw2wann.in > pw2wann.out
-/home/nicola/CODES/q-e-kcw/bin/wannier90.x $SEEDNAME.win
+$ECHO "  Running Wannierization block 1 for $PREFIX...\c"
+$W90_COMMAND -pp $SEEDNAME.win
+$PW2W90_COMMAND -in pw2wann.in > pw2wann.out
+$W90_COMMAND $SEEDNAME.win
+rm k_points.txt
+$ECHO "DONE"
 cd ../
 
 if [ ! -d wann_block2 ]; then  mkdir wann_block2 ; fi
 cd wann_block2
+
+$KMESH_COMMAND $nk $nk $nk wann > k_points.txt
+
 cat > $SEEDNAME.win << EOF
 num_bands         =   5
 num_wann          =   5
@@ -432,73 +329,10 @@ end kpoint_path
 
 
 
-mp_grid      = 4 4 4
+mp_grid      = $nk $nk $nk
 
 begin kpoints
-  0.00000000  0.00000000  0.00000000
-  0.00000000  0.00000000  0.25000000
-  0.00000000  0.00000000  0.50000000
-  0.00000000  0.00000000  0.75000000
-  0.00000000  0.25000000  0.00000000
-  0.00000000  0.25000000  0.25000000
-  0.00000000  0.25000000  0.50000000
-  0.00000000  0.25000000  0.75000000
-  0.00000000  0.50000000  0.00000000
-  0.00000000  0.50000000  0.25000000
-  0.00000000  0.50000000  0.50000000
-  0.00000000  0.50000000  0.75000000
-  0.00000000  0.75000000  0.00000000
-  0.00000000  0.75000000  0.25000000
-  0.00000000  0.75000000  0.50000000
-  0.00000000  0.75000000  0.75000000
-  0.25000000  0.00000000  0.00000000
-  0.25000000  0.00000000  0.25000000
-  0.25000000  0.00000000  0.50000000
-  0.25000000  0.00000000  0.75000000
-  0.25000000  0.25000000  0.00000000
-  0.25000000  0.25000000  0.25000000
-  0.25000000  0.25000000  0.50000000
-  0.25000000  0.25000000  0.75000000
-  0.25000000  0.50000000  0.00000000
-  0.25000000  0.50000000  0.25000000
-  0.25000000  0.50000000  0.50000000
-  0.25000000  0.50000000  0.75000000
-  0.25000000  0.75000000  0.00000000
-  0.25000000  0.75000000  0.25000000
-  0.25000000  0.75000000  0.50000000
-  0.25000000  0.75000000  0.75000000
-  0.50000000  0.00000000  0.00000000
-  0.50000000  0.00000000  0.25000000
-  0.50000000  0.00000000  0.50000000
-  0.50000000  0.00000000  0.75000000
-  0.50000000  0.25000000  0.00000000
-  0.50000000  0.25000000  0.25000000
-  0.50000000  0.25000000  0.50000000
-  0.50000000  0.25000000  0.75000000
-  0.50000000  0.50000000  0.00000000
-  0.50000000  0.50000000  0.25000000
-  0.50000000  0.50000000  0.50000000
-  0.50000000  0.50000000  0.75000000
-  0.50000000  0.75000000  0.00000000
-  0.50000000  0.75000000  0.25000000
-  0.50000000  0.75000000  0.50000000
-  0.50000000  0.75000000  0.75000000
-  0.75000000  0.00000000  0.00000000
-  0.75000000  0.00000000  0.25000000
-  0.75000000  0.00000000  0.50000000
-  0.75000000  0.00000000  0.75000000
-  0.75000000  0.25000000  0.00000000
-  0.75000000  0.25000000  0.25000000
-  0.75000000  0.25000000  0.50000000
-  0.75000000  0.25000000  0.75000000
-  0.75000000  0.50000000  0.00000000
-  0.75000000  0.50000000  0.25000000
-  0.75000000  0.50000000  0.50000000
-  0.75000000  0.50000000  0.75000000
-  0.75000000  0.75000000  0.00000000
-  0.75000000  0.75000000  0.25000000
-  0.75000000  0.75000000  0.50000000
-  0.75000000  0.75000000  0.75000000
+$(cat k_points.txt)
 end kpoints
 EOF
 
@@ -511,14 +345,21 @@ cat >pw2wann.in <<EOF
  write_unk  = .false.
 /
 EOF
-/home/nicola/CODES/q-e-kcw/bin/wannier90.x -pp $SEEDNAME.win
-/home/nicola/CODES/q-e-kcw/bin/pw2wannier90.x -in pw2wann.in > pw2wann.out
-/home/nicola/CODES/q-e-kcw/bin/wannier90.x $SEEDNAME.win
+
+$ECHO "  Running Wannierization block 2 for $PREFIX...\c"
+$W90_COMMAND -pp $SEEDNAME.win
+$PW2W90_COMMAND -in pw2wann.in > pw2wann.out
+$W90_COMMAND $SEEDNAME.win
+rm k_points.txt
+$ECHO "DONE"
 cd ../
 
 
 if [ ! -d wann_block3 ]; then  mkdir wann_block3 ; fi
 cd wann_block3
+
+$KMESH_COMMAND $nk $nk $nk wann > k_points.txt
+
 cat > $SEEDNAME.win << EOF
 num_bands         =   4
 num_wann          =   4
@@ -564,73 +405,10 @@ end kpoint_path
 
 
 
-mp_grid      = 4 4 4
+mp_grid      = $nk $nk $nk
 
 begin kpoints
-  0.00000000  0.00000000  0.00000000
-  0.00000000  0.00000000  0.25000000
-  0.00000000  0.00000000  0.50000000
-  0.00000000  0.00000000  0.75000000
-  0.00000000  0.25000000  0.00000000
-  0.00000000  0.25000000  0.25000000
-  0.00000000  0.25000000  0.50000000
-  0.00000000  0.25000000  0.75000000
-  0.00000000  0.50000000  0.00000000
-  0.00000000  0.50000000  0.25000000
-  0.00000000  0.50000000  0.50000000
-  0.00000000  0.50000000  0.75000000
-  0.00000000  0.75000000  0.00000000
-  0.00000000  0.75000000  0.25000000
-  0.00000000  0.75000000  0.50000000
-  0.00000000  0.75000000  0.75000000
-  0.25000000  0.00000000  0.00000000
-  0.25000000  0.00000000  0.25000000
-  0.25000000  0.00000000  0.50000000
-  0.25000000  0.00000000  0.75000000
-  0.25000000  0.25000000  0.00000000
-  0.25000000  0.25000000  0.25000000
-  0.25000000  0.25000000  0.50000000
-  0.25000000  0.25000000  0.75000000
-  0.25000000  0.50000000  0.00000000
-  0.25000000  0.50000000  0.25000000
-  0.25000000  0.50000000  0.50000000
-  0.25000000  0.50000000  0.75000000
-  0.25000000  0.75000000  0.00000000
-  0.25000000  0.75000000  0.25000000
-  0.25000000  0.75000000  0.50000000
-  0.25000000  0.75000000  0.75000000
-  0.50000000  0.00000000  0.00000000
-  0.50000000  0.00000000  0.25000000
-  0.50000000  0.00000000  0.50000000
-  0.50000000  0.00000000  0.75000000
-  0.50000000  0.25000000  0.00000000
-  0.50000000  0.25000000  0.25000000
-  0.50000000  0.25000000  0.50000000
-  0.50000000  0.25000000  0.75000000
-  0.50000000  0.50000000  0.00000000
-  0.50000000  0.50000000  0.25000000
-  0.50000000  0.50000000  0.50000000
-  0.50000000  0.50000000  0.75000000
-  0.50000000  0.75000000  0.00000000
-  0.50000000  0.75000000  0.25000000
-  0.50000000  0.75000000  0.50000000
-  0.50000000  0.75000000  0.75000000
-  0.75000000  0.00000000  0.00000000
-  0.75000000  0.00000000  0.25000000
-  0.75000000  0.00000000  0.50000000
-  0.75000000  0.00000000  0.75000000
-  0.75000000  0.25000000  0.00000000
-  0.75000000  0.25000000  0.25000000
-  0.75000000  0.25000000  0.50000000
-  0.75000000  0.25000000  0.75000000
-  0.75000000  0.50000000  0.00000000
-  0.75000000  0.50000000  0.25000000
-  0.75000000  0.50000000  0.50000000
-  0.75000000  0.50000000  0.75000000
-  0.75000000  0.75000000  0.00000000
-  0.75000000  0.75000000  0.25000000
-  0.75000000  0.75000000  0.50000000
-  0.75000000  0.75000000  0.75000000
+$(cat k_points.txt)
 end kpoints
 EOF
 
@@ -644,16 +422,20 @@ cat >pw2wann.in <<EOF
 /
 EOF
 
-/home/nicola/CODES/q-e-kcw/bin/wannier90.x -pp $SEEDNAME.win
-/home/nicola/CODES/q-e-kcw/bin/pw2wannier90.x -in pw2wann.in > pw2wann.out
-/home/nicola/CODES/q-e-kcw/bin/wannier90.x $SEEDNAME.win
+$ECHO "  Running Wannierization block 3 for $PREFIX...\c"
+$W90_COMMAND -pp $SEEDNAME.win
+$PW2W90_COMMAND -in pw2wann.in > pw2wann.out
+$W90_COMMAND $SEEDNAME.win
+rm k_points.txt
+$ECHO "DONE" 
+
 cd ../
 
-echo Merge Wannier
-/home/nicola/CODES/q-e-kcw/bin/merge_wann.x U wann_block1/wann_u.mat wann_block2/wann_u.mat wann_block3/wann_u.mat  > merge_U.out 
-/home/nicola/CODES/q-e-kcw/bin/merge_wann.x centres wann_block1/wann_centres.xyz wann_block2/wann_centres.xyz wann_block3/wann_centres.xyz > merge_centres.out 
+$ECHO "  Running merge_wann.x for $PREFIX...\c"
+$MERGE_WANN_COMMAND U       wann_block1/wann_u.mat       wann_block2/wann_u.mat       wann_block3/wann_u.mat       > merge_U.out 
+$MERGE_WANN_COMMAND centres wann_block1/wann_centres.xyz wann_block2/wann_centres.xyz wann_block3/wann_centres.xyz > merge_centres.out 
+$ECHO "DONE"
 
-echo pw2w902kcw
 cat > kc.w2ki << EOF 
 &CONTROL
    prefix='$PREFIX'
@@ -661,9 +443,9 @@ cat > kc.w2ki << EOF
    kcw_iverbosity   = 1
    kcw_at_ks        = .false.
    calculation      = 'wann2kcw'
-   mp1              = 4
-   mp2              = 4
-   mp3              = 4
+   mp1              = $nk
+   mp2              = $nk
+   mp3              = $nk
    read_unitary_matrix = .true.
    l_vcut           = .true.
    kcw_iverbosity    = 2
@@ -677,4 +459,7 @@ cat > kc.w2ki << EOF
    has_disentangle  = .false.
 /
 EOF
-/home/nicola/CODES/q-e-kcw/bin/kcw.x -in kc.w2ki > kc.w2ko
+
+$ECHO "  Running kcw.x interface for $PREFIX...\c"
+$KCW_COMMAND -in kc.w2ki > kc.w2ko
+$ECHO "DONE" 
